'''
lead_DNA = "CGGCCGGAGCTCTGCTTTACCACTCTAACCGTCTTACCAACAACCCGTATGAGTCCTTACGCTGCCAAAGGGGCGCTATCACAGCAGGTCAAGCGAGATCCAGCCCTCCAGCTTGCCCCCGAGACCTCTGGACCTCATCATCTGTGATAATTGGCCCGTATGGTGTGAACGTGGTGCAGGATCAACATTGTACATCTCTGTCCTCGATATAACGAATCAACCGAGCAACTCCTATGGAGAGCAACCAGTGAAGGGTGCCCGCAAGTACCAGTGCCCTGTGTCTATCGTCATCATTTCACTGAGCATGGAGTGAAACTAGTCAGAATGCCTTGATGTGTAGTATGATTGGGTATTCTATGTCGTTTCCTCGATTATCACTTGCGAGTGTTTGCACTAGAACAGCAGTCCTTAACTGAACCCTAAAACACGTCTAACTTAAAGCCGACTGCATGCATGGGATTAATATTCTCGTGCTGGCGCGCGACCACCGGATGGTCCGTAATAGCTGTCCTAATGGCTCGCTTAAGAACCCAGGACTTTGGAGAAATAATTGACTGATTGCCTCCTTAGACCGTTTCTACACTAGAACAATAGTGATAAACTAGGGTGAAACTTCCGCTATGTGGGTGTGCACGTAAACCCTAGACCTGCAACAACAAAGACAGCATTTCTGGATTGATTCGAAAATAAATTTGCGGATTCGCGCCCTATCGCTCTTTACGGGAATAAGGAACTCATGTGGAGTGATTATCCTATACTGGATGAATTAGAACAGTAAGATGTTAAATTTGAGCTGTCAGACCCCTCTTCCGTGAGT"
compl_bases = str.maketrans({'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'})

lag_DNA = lead_DNA.translate(compl_bases)

#the complementary strand must be read backwards
lag_DNA = lag_DNA[::-1]

print(lag_DNA)'''


#or with biopython
from Bio.Seq import Seq
with open(r"assignment #1/revc.txt", 'r') as f:
    s = Seq(f.read())

my_compl = s.reverse_complement()
print(my_compl)
